### ISSUE TITLE
drop the `certfilepath` argument which is definitely wrong and it fails to connect

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/BTCPayServer.Lightning#160]
Looks like this broke something - it instructs the users to drop the `certfilepath` argument which is definitely wrong and it fails to connect. However it still works in some other instance on regtest so I'm not really sure what's going on. Do you see anything obvious?

To be precise, BTCPay now can create invoice but can't see that it was paid.

_Originally posted by @Kixunil in https://github.com/btcpayserver/btcpayserver/issues/5422#issuecomment-1937105604_

**Comment by Kukks** [comment]
Note; we need to release a new version of lnd lib for btcpay

**Comment by Kixunil** [comment]
Does that also fix the connection issue?
