### ISSUE TITLE
Regenerate new fresh macaroons safely

### ISSUE THREAD

**Issue by whiteyhat** [btcpayserver/BTCPayServer.Lightning#18]
Hey 👋 

How can I safely create new macaroons for my lnd btcpay instance?

**Comment by NicolasDorier** [comment]
https://docs.btcpayserver.org/faq-and-common-issues/faq-lightningnetwork#lnd-connection-issues-after-an-update

**Comment by whiteyhat** [comment]
Thank you 🙏
