### ISSUE TITLE
Fix ptarmigan tests

### ISSUE THREAD

**Issue by NicolasDorier** [btcpayserver/BTCPayServer.Lightning#20]
@nayuta-kohei pTarmigan was breaking the CI: https://circleci.com/gh/btcpayserver/BTCPayServer.Lightning

I removed the tests on https://github.com/btcpayserver/BTCPayServer.Lightning/commit/7cf06ca4d79858934d319aa03e224b30205e8217 .

Please fix the bug and make it works again.

**Comment by NicolasDorier** [comment]
Also reverted https://github.com/btcpayserver/BTCPayServer.Lightning/commit/3211e655e8eb6a12765ad0e5314c6b9a8d69d9f8

**Comment by dennisreimann** [comment]
After 404b0605606617a04889e2999bf77707eba824b4 this issue is now obsolete.

**Comment by NicolasDorier** [comment]
closing ptarmigan is archived so we stopped supporting it.
