### ISSUE TITLE
Amount is wrong for `p` amount units

### ISSUE THREAD

**Issue by Sword-Smith** [btcpayserver/BTCPayServer.Lightning#25]
Version used: BTCPayServer.Lightning.Common; 1.1.0.16

`lnbc9678785340p1pwmna7lpp5gc3xfm08u9qy06djf8dfflhugl6p7lgza6dsjxq454gxhj9t7a0sd8dgfkx7cmtwd68yetpd5s9xar0wfjn5gpc8qhrsdfq24f5ggrxdaezqsnvda3kkum5wfjkzmfqf3jkgem9wgsyuctwdus9xgrcyqcjcgpzgfskx6eqf9hzqnteypzxz7fzypfhg6trddjhygrcyqezcgpzfysywmm5ypxxjemgw3hxjmn8yptk7untd9hxwg3q2d6xjcmtv4ezq7pqxgsxzmnyyqcjqmt0wfjjq6t5v4khxxqyjw5qcqp2rzjq0gxwkzc8w6323m55m4jyxcjwmy7stt9hwkwe2qxmy8zpsgg7jcuwz87fcqqeuqqqyqqqqlgqqqqn3qq9qs4x9qlmd57lq7wwr23n3a6pkayy3jpfucyptlncs2maswe3dnnjy3ce2cgrvykmxlfpvn6ptqfqz4df5uaulvd4hjkckuqxrqqkz8jgphputwh`

```
paymentRequest = BOLT11PaymentRequest.Parse(invoice, NBitcoin.Network.Main);
aymentRequest.MinimumAmount.MilliSatoshi.ToString();
paymentRequest.MinimumAmount.ToString();
```

Prints `"9678785340"` and `"0.0967878534"`. 

The correct result would have been
`"967878534"` and `"0.00967878534"`. 

So there seems to be an error when parsing the `p` unit specifier. `p` is 10^(-12) BTC and not 10^(-11) BTC.

**Comment by Sword-Smith** [comment]
Temporary workaround that should also produce correct results once this bug is fixed:

```
            Match m = Regex.Match(invoice, @"ln(bc|tb)(\d{1,12})p1.*");
            long realMilliSatoshi;
            if (m.Success)
            {
                long picoBtc = Int64.Parse(m.Groups[2].Value);
                if (picoBtc == paymentRequest.MinimumAmount.MilliSatoshi)
                {
                    // The bug is not fixed
                    realMilliSatoshi = paymentRequest.MinimumAmount.MilliSatoshi / 10;
                }
                else if (picoBtc == 10 * paymentRequest.MinimumAmount.MilliSatoshi)
                {
                    // The bug is fixed
                    realMilliSatoshi = paymentRequest.MinimumAmount.MilliSatoshi;
                }
                else
                {
                    throw new Exception($"Unknown amount for invoice: {invoice}.");
                }
            }
            else
            {
                realMilliSatoshi = paymentRequest.MinimumAmount.MilliSatoshi;
            }
```

**Comment by NicolasDorier** [comment]
Your code can be broken via overflow.

**Comment by NicolasDorier** [comment]
I decided to remove support for pico for the following reasons:

1. It is impossible to represent 21 millions bitcoin in pico on a `long` without overflow
2. Nobody use `pico`, even APIs are using milli satoshi (which oddly can't be represented in BOLT11)
3. We can't fix `LightMoneyUnit` enum `ulong` without having risk of somebody sending 10 times more money than they should

I am open for pull request if somebody wants to fix it and properly test

**Comment by Sword-Smith** [comment]
1. You are right but I don't think that's a practical problem. If you are going to send over 1m BTC in a transaction, my guess would be that you did it on chain :) And if you are afraid of wrong results in this very hypothetical scenario, I would suggest that you throw an exception in that case. That would be better than giving wrong results.
2. Blockstream's store uses pico, and so does the Android app Bitcoin Lightning Wallet in certain cases.

I have only used Lightning on main net a few times, and have encountered `p` twice from two diferent sources. I need `p` support.

I would suggest that you make a special case check (which will never be encountered in production) that if you use the `p` amounts, the maximum limit is 9.2m. If you use any other unit, you can go beyond that.

**Comment by Sword-Smith** [comment]
> 
> 
> Your code can be broken via overflow.

I don't think so since I only capture up to 12 digits via the regex. In my own code, I put in up to 14 but same difference.

**Comment by Sword-Smith** [comment]
Alternatively: Since the resolution of invoices are 10^(-11) but `p` is 10^(-12), any `p` amount **must** end on a "0". So you could just not count this 0 avoid the problem that way.

**Comment by NicolasDorier** [comment]
@Sword-Smith ok I will take a look at that.

**Comment by NicolasDorier** [comment]
@Sword-Smith making a new release with your suggestion, I think this is best. I just won't accept pico if not a multiple of 10
