### ISSUE TITLE
test seems failing in master

### ISSUE THREAD

**Issue by joemphilips** [btcpayserver/BTCPayServer.Lightning#3]
When I tried to run test, I encountered the issue that `EnsureConnectedToDestinations` function never finishes.
taking look closely, I discovered that when the destination is lnd, PayResult will always be `CouldNotFindRoute` but OpenChannleResult is always `AlreadyExists`
lnd returns empty list when I called `listpeers` manually, and when I try to connect to sender manually with `connect` RPC, it returns following error

```
[lncli] rpc error: code = Unknown desc = chain backend is still syncing, server not active yet
```

block count of lnd and bitcoind is same.
All I could come up with as a reason was  this bug (https://github.com/lightningnetwork/lnd/issues/2195)
If this is the case, I suppose bumping the btcpayserver/lnd docker version is necessary.
(It might be nice if there are guidelines about lnd fork of btcpayserver. e.g. why it requires the fork in the first place, what is the difference from upstream.)

**Comment by NicolasDorier** [comment]
This is strange, it works on my machine.
You can see the difference in the source of btcpayserver/lnd repo.

I link the dockerfile and github repo of images on https://github.com/btcpayserver/btcpayserver-docker

Try to do `docker-compose down --v` and start again.

**Comment by joemphilips** [comment]
You are right. deleting volumes and starting over worked for me ... It seems LND sometimes get stuck for quirky reason. Never mind.

**Comment by NicolasDorier** [comment]
Yes I noticed that. Lightning is not super stable on regtest for some reasons.
