### ISSUE TITLE
Allow insecure connections to Charge (skip https validation) 

### ISSUE THREAD

**Issue by nitramiz** [btcpayserver/BTCPayServer.Lightning#34]
**Describe the problem/bug**

I'm trying to connect to an existing lightning + charge node that's running on another box, but the charge port has been forwarded over SSH to the btcpayserver one.

**Your environment**
* Version of BTCPay Server: `1.0.4.4`
* Deployment method: independent containers running btcpayserver, nbxplorer and bitcoin RPC port-forwarded
* Other relevant environment details: in order to get around the https requirement for connecting to charge, I've added a https reverse proxy that's listening on 8080 and `proxy_pass`ing to the charge port (9112) and a self-signed localhost cert

**Logs (if applicable)**
Nothing relevant, just New Block events.

**Setup Parameters**
If you're reporting a deployment issue run `. btcpay-setup.sh -i` and paste your the paremeters by obscuring private information.
btcpay-setup.sh not used

**To Reproduce**
1. Go to Store
2. Click on Lightning BTC Modify
3. Scroll down to Url and enter `type=charge;url=https://localhost8080;api-token=xxxx`
4. See error ` Error while connecting to the API (The SSL connection could not be established, see inner exception.)`

It'd be great if there's an `allowinsecure=true` option for charge as well, in order to skip https validation.

**Comment by nitramiz** [comment]
Sorry for bringing this up again, but I tested https://github.com/btcpayserver/btcpayserver/commit/00f4691f383ab755c0fb4419de67863bf11ba14c by building a docker image and runs fine, but I get an error: `The url must be HTTPS` (https://github.com/btcpayserver/btcpayserver/blob/master/BTCPayServer/Controllers/StoresController.LightningLike.cs#L98)  

Connection string used:
`type=charge;server=http://localhost:8080/;api-token=some_token;allowinsecure=true`

**Comment by NicolasDorier** [comment]
did you tried again recently? I think I made a new release since when you last reported.

**Comment by nitramiz** [comment]
@NicolasDorier yeah, I did and was able to almost connect. I ran into https://github.com/btcpayserver/BTCPayServer.Lightning/issues/34 (not being able to connect BTCPay to a non-public node)
