### ISSUE TITLE
Missing CancellationTokens for some methods in ILightningClient

### ISSUE THREAD

**Issue by konak** [btcpayserver/BTCPayServer.Lightning#68]
Some methods in ILightningClient do not have CancellationToken as parameter:

        Task<BitcoinAddress> GetDepositAddress();
        Task<ConnectionResult> ConnectTo(NodeInfo nodeInfo);
        Task CancelInvoice(string invoiceId);

Is that Ok ? Because in some cases they can became an issue for client and backend responsiveness.

**Comment by dennisreimann** [comment]
@Kukks Is there a special reason why we don't have them for `ConnectTo` and `GetDepositAddress`? For `CancelInvoice` we are explicit and passing a `CancellationToken.None` to the underlying implementations, but for the others we are just omitting the CT, though I think we should pass it.

**Comment by Kukks** [comment]
> @Kukks Is there a special reason why we don't have them for `ConnectTo` and `GetDepositAddress`? For `CancelInvoice` we are explicit and passing a `CancellationToken.None` to the underlying implementations, but for the others we are just omitting the CT, though I think we should pass it.

ack for adding them

**Comment by dennisreimann** [comment]
@Kukks I can do that next — what about the `CancelInvoice` one? Are we omitting it consciously or shall it get added too?

**Comment by NicolasDorier** [comment]
Pushed new packages.
